USE `quest_bd`;

CREATE TABLE IF NOT EXISTS `user` (
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`login` VARCHAR(255) NOT NULL UNIQUE,
	`password` CHAR(32) NOT NULL,
	/*
	 * 0 - администратор (Role.ADMINISTRATOR)
	 * 1 - менеджер (Role.Manager)
	 * 2 - клиент (Role.Client)
	 */
	`role` TINYINT NOT NULL CHECK (`role` IN (0, 1, 2)),
	PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS `client` (
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(255) NOT NULL,
	`surname` VARCHAR(255) NOT NULL,
	`patronymic` VARCHAR(255) NOT NULL,
	`years` integer(3) NOT NULL,
	`email` VARCHAR(255) NOT NULL,
	`phone` VARCHAR(255) NOT NULL,
	PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS `author_quest` (
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(255) NOT NULL,
	`surname` VARCHAR(255) NOT NULL,
	`patronymic` VARCHAR(255) NOT NULL,
	`year_of_birth` INTEGER NOT NULL,
	`year_of_death` INTEGER,
	PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS `quest` (
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`title` VARCHAR(255) NOT NULL,
	`level` INTEGER(1) NOT NULL,
	`max_people` INTEGER(1) NOT NULL,
	`author_id` INTEGER NOT NULL ,
	CONSTRAINT PK_quest PRIMARY KEY (`id`),
	CONSTRAINT FK_quest_author_quest  FOREIGN KEY (`author_id`) REFERENCES `author_quest` (`id`)
) ENGINE=INNODB DEFAULT CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS `quest_place` (
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`title` VARCHAR(255) NOT NULL,
	`address` VARCHAR(255) NOT NULL,
	`phone` VARCHAR(255) NOT NULL,
	`quest_id` INTEGER NOT NULL ,
	PRIMARY KEY (`id`),
	FOREIGN KEY (`quest_id`) REFERENCES `quest` (`id`)
)ENGINE=INNODB DEFAULT CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS `used_quest` (
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`title` VARCHAR(255) NOT NULL,
	`date` DATE NOT NULL,
	`level` INTEGER(1) NOT NULL,
	`client_id` INTEGER NOT NULL ,
	PRIMARY KEY (`id`),
	FOREIGN KEY (`client_id`) REFERENCES `client` (`id`)
)ENGINE=INNODB DEFAULT CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS `review` (
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`message` VARCHAR(255) NOT NULL,
	`date` DATE NOT NULL,
	`client_id` INTEGER NOT NULL ,
	PRIMARY KEY (`id`),
	FOREIGN KEY (`client_id`) REFERENCES `client` (`id`)
)ENGINE=INNODB DEFAULT CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS `my_booking` (
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`date` DATE NOT NULL,
	`client_id` INTEGER NOT NULL,
	`quest_id` INTEGER NOT NULL,
	PRIMARY KEY (`id`),
	FOREIGN KEY (`client_id`) REFERENCES `client` (`id`),
	FOREIGN KEY (`quest_id`) REFERENCES `quest` (`id`)
)ENGINE=INNODB DEFAULT CHARACTER SET utf8;
