//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.05 at 04:53:08 PM MSK 
//


package by.epam.xml.entity;

import java.math.BigInteger;


/**
 * <p>Java class for Characteristics complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Characteristics">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="stars" type="{http://www.training.by/vouchers}Stars"/>
 *         &lt;element name="nutrition" type="{http://www.training.by/vouchers}Nutrition"/>
 *         &lt;element name="room" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="TV" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="WI_FI" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="air_conditioning" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public class Characteristics {

    protected int stars;
    protected Nutrition nutrition;
    protected BigInteger room;
    protected boolean tv;
    protected boolean wifi;
    protected boolean airConditioning;

    /**
     * Gets the value of the stars property.
     * 
     */
    public int getStars() {
        return stars;
    }

    /**
     * Sets the value of the stars property.
     * 
     */
    public void setStars(int value) {
        this.stars = value;
    }

    /**
     * Gets the value of the nutrition property.
     * 
     * @return
     *     possible object is
     *     {@link Nutrition }
     *     
     */
    public Nutrition getNutrition() {
        return nutrition;
    }

    /**
     * Sets the value of the nutrition property.
     * 
     * @param value
     *     allowed object is
     *     {@link Nutrition }
     *     
     */
    public void setNutrition(Nutrition value) {
        this.nutrition = value;
    }

    /**
     * Gets the value of the room property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRoom() {
        return room;
    }

    /**
     * Sets the value of the room property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRoom(BigInteger value) {
        this.room = value;
    }

    /**
     * Gets the value of the tv property.
     * 
     */
    public boolean isTV() {
        return tv;
    }

    /**
     * Sets the value of the tv property.
     * 
     */
    public void setTV(boolean value) {
        this.tv = value;
    }

    /**
     * Gets the value of the wifi property.
     * 
     */
    public boolean isWIFI() {
        return wifi;
    }

    /**
     * Sets the value of the wifi property.
     * 
     */
    public void setWIFI(boolean value) {
        this.wifi = value;
    }

    /**
     * Gets the value of the airConditioning property.
     * 
     */
    public boolean isAirConditioning() {
        return airConditioning;
    }

    /**
     * Sets the value of the airConditioning property.
     * 
     */
    public void setAirConditioning(boolean value) {
        this.airConditioning = value;
    }

    public boolean isTv() {
        return tv;
    }

    public void setTv(boolean tv) {
        this.tv = tv;
    }

    public boolean isWifi() {
        return wifi;
    }

    public void setWifi(boolean wifi) {
        this.wifi = wifi;
    }

    @Override
    public String toString() {
        return "Characteristics{" +
                "stars=" + stars +
                ", nutrition=" + nutrition +
                ", room=" + room +
                ", tv=" + tv +
                ", wifi=" + wifi +
                ", airConditioning=" + airConditioning +
                '}';
    }
}
